import os
import io
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, KeepTogether, PageBreak
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas
from PIL import Image as PILImage

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically track and print the total page count
    along with professional footer branding on every page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(HexColor("#4B5563")) # gray-600
        
        # 1. Header decoration (only on page 2 and later)
        if self._pageNumber > 1:
            self.drawString(36, 805, "AI Crop Disease Analysis Report")
            self.drawRightString(559, 805, "CropDiseaseAI Diagnostics")
            self.setStrokeColor(HexColor("#E5E7EB")) # gray-200
            self.setLineWidth(0.5)
            self.line(36, 798, 559, 798)
            
        # 2. Footer decoration (on all pages)
        self.setStrokeColor(HexColor("#E5E7EB")) # gray-200
        self.setLineWidth(0.5)
        self.line(36, 45, 559, 45)
        
        self.drawString(36, 30, "Generated by CropDiseaseAI | Confidential Diagnostic Report")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(559, 30, page_str)
        
        self.restoreState()


def generate_pdf_report(data, username=None):
    """
    Generates a professional A4 PDF bytes buffer from analysis results.
    Supports single dictionary report or list/collection of reports.
    """
    # Check if this is a bulk reports compilation
    if isinstance(data, list):
        reports_list = data
    elif isinstance(data, dict) and "reports" in data:
        reports_list = data["reports"]
    else:
        reports_list = [data]

    # Setup Document Layout
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=54,
        bottomMargin=64
    )
    
    # Design System & Typography
    PRIMARY_GREEN = HexColor("#15803D")   # Green 700
    LIGHT_GREEN = HexColor("#F0FDF4")     # Green 50
    TEXT_DARK = HexColor("#1F2937")       # Gray 800
    TEXT_MUTED = HexColor("#4B5563")      # Gray 600
    BORDER_COLOR = HexColor("#86EFAC")    # Green 300
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=PRIMARY_GREEN,
        spaceAfter=2
    )
    
    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=PRIMARY_GREEN,
        spaceBefore=14,
        spaceAfter=6,
        keepWithNext=True
    )
    
    subsection_heading = ParagraphStyle(
        "SubsectionHeading",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=14,
        textColor=TEXT_DARK,
        spaceBefore=8,
        spaceAfter=4,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        "BodyTextDark",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13.5,
        textColor=TEXT_DARK,
        spaceAfter=4
    )
    
    body_bold = ParagraphStyle(
        "BodyTextBold",
        parent=body_style,
        fontName="Helvetica-Bold"
    )
    
    disclaimer_style = ParagraphStyle(
        "DisclaimerText",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=8,
        leading=11.5,
        textColor=TEXT_MUTED,
        spaceBefore=6
    )

    story = []

    for r_idx, report in enumerate(reports_list):
        # Parse current report data
        crop_name = report.get("crop_name", "N/A")
        disease_name = report.get("disease_name", "N/A")
        confidence = report.get("confidence", "N/A")
        severity = report.get("severity", "N/A")
        symptoms = report.get("symptoms", [])
        possible_causes = report.get("possible_causes", [])
        prevention = report.get("prevention", [])
        treatment = report.get("treatment", [])
        fertilizer = report.get("fertilizer_recommendation", "No custom fertilizer recommendations available.")
        watering = report.get("watering_advice", "No custom watering advice available.")
        notes = report.get("additional_notes", "No additional notes provided.")
        filename = report.get("filename", "")
        treatment_guidance = report.get("treatment_guidance", None)
        calculator_metrics = report.get("calculator_metrics", None)

        # Logo & Banner Header
        logo_path = "static/images/logo.png"
        if os.path.exists(logo_path):
            logo_img = Image(logo_path, width=42, height=42)
        else:
            logo_img = Paragraph("🌱", ParagraphStyle("LogoText", fontName="Helvetica", fontSize=28, leading=32))
            
        title_text = "<b>AI Crop Disease Analysis Report</b><br/><font size=8.5 color='#4B5563'>Generated by CropDiseaseAI Diagnostics</font>"
        title_p = Paragraph(title_text, title_style)
        
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        meta_html = f"<b>Date:</b> {date_str}<br/><b>Prepared For:</b> {username or 'Guest User'}"
        meta_p = Paragraph(meta_html, body_style)
        
        header_table = Table([[logo_img, title_p, meta_p]], colWidths=[55, 300, 168])
        header_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 2),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        story.append(header_table)
        
        # Header Accent line
        divider = Table([[""]], colWidths=[523], rowHeights=[2])
        divider.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (0,0), PRIMARY_GREEN),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        story.append(divider)
        story.append(Spacer(1, 12))

        # General Information & Leaf Image Card
        details_data = [
            [Paragraph("<b>Crop Name:</b>", body_style), Paragraph(crop_name, body_style)],
            [Paragraph("<b>Disease Identified:</b>", body_style), Paragraph(disease_name, body_style)],
            [Paragraph("<b>Confidence Level:</b>", body_style), Paragraph(confidence, body_style)],
            [Paragraph("<b>Severity Level:</b>", body_style), Paragraph(severity, body_style)],
        ]
        details_table = Table(details_data, colWidths=[110, 190])
        details_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
        ]))
        
        # Scale Leaf Image keeping aspect ratio
        img_path = f"uploads/{filename}"
        if filename and os.path.exists(img_path):
            try:
                with PILImage.open(img_path) as pil_img:
                    w, h = pil_img.size
                    aspect = w / h
                    if aspect >= 4/3:
                        img_w = 180
                        img_h = int(180 / aspect)
                    else:
                        img_h = 135
                        img_w = int(135 * aspect)
                report_img = Image(img_path, width=img_w, height=img_h)
            except Exception:
                report_img = Paragraph("<i>[Leaf Image Uploaded]</i>", body_style)
        else:
            report_img = Paragraph("<i>[No leaf image uploaded]</i>", body_style)

        # Nest Details & Image inside a styled card Table
        summary_data = [[details_table, report_img]]
        summary_table = Table(summary_data, colWidths=[310, 213])
        summary_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BACKGROUND', (0,0), (-1,-1), LIGHT_GREEN),
            ('BOX', (0,0), (-1,-1), 0.75, BORDER_COLOR),
            ('TOPPADDING', (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('LEFTPADDING', (0,0), (-1,-1), 12),
            ('RIGHTPADDING', (0,0), (-1,-1), 12),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 10))

        # Diagnosis Section: Symptoms & Causes side-by-side
        story.append(Paragraph("Diagnostic Finding Details", section_heading))
        
        symptom_bullets = "".join([f"• {s}<br/>" for s in symptoms]) if symptoms else "• None described."
        cause_bullets = "".join([f"• {c}<br/>" for c in possible_causes]) if possible_causes else "• None described."
        
        diag_data = [
            [Paragraph("<b>🔍 Observed Symptoms:</b>", body_bold), Paragraph("<b>⚠️ Possible Causes:</b>", body_bold)],
            [Paragraph(symptom_bullets, body_style), Paragraph(cause_bullets, body_style)]
        ]
        diag_table = Table(diag_data, colWidths=[256, 267])
        diag_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BACKGROUND', (0,0), (-1,-1), HexColor("#FAFAFA")),
            ('LINEBELOW', (0,0), (1,0), 0.5, HexColor("#E5E7EB")),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 8),
            ('RIGHTPADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(diag_table)
        story.append(Spacer(1, 10))

        # Management & Action Plan
        story.append(Paragraph("Agricultural Management Recommendations", section_heading))
        
        prevention_bullets = "".join([f"• {p}<br/>" for p in prevention]) if prevention else "• None described."
        treatment_bullets = "".join([f"• {t}<br/>" for t in treatment]) if treatment else "• None described."
        
        action_data = [
            [Paragraph("<b>🛡️ Prevention Measures:</b>", body_bold), Paragraph("<b>💊 Recommended Treatments:</b>", body_bold)],
            [Paragraph(prevention_bullets, body_style), Paragraph(treatment_bullets, body_style)]
        ]
        action_table = Table(action_data, colWidths=[256, 267])
        action_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BACKGROUND', (0,0), (-1,-1), HexColor("#FAFAFA")),
            ('LINEBELOW', (0,0), (1,0), 0.5, HexColor("#E5E7EB")),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING', (0,0), (-1,-1), 8),
            ('RIGHTPADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(action_table)
        story.append(Spacer(1, 10))

        # Nutrients, Watering & Additional Notes
        notes_data = [
            [Paragraph("<b>🧪 Fertilizer Recommendation:</b>", body_bold), Paragraph(fertilizer, body_style)],
            [Paragraph("<b>💧 Irrigation & Water Advice:</b>", body_bold), Paragraph(watering, body_style)],
            [Paragraph("<b>📝 Additional Notes:</b>", body_bold), Paragraph(notes, body_style)],
        ]
        notes_table = Table(notes_data, colWidths=[150, 373])
        notes_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
        ]))
        story.append(notes_table)
        story.append(Spacer(1, 10))

        # Verified Treatment Guidance Section (if available)
        if treatment_guidance:
            tg_elements = []
            tg_elements.append(Paragraph("Verified Agricultural Treatment Guidance", section_heading))
            
            # Organic step block
            if treatment_guidance.get("organic_treatment"):
                tg_elements.append(Paragraph("<b>Organic Treatment Protocol:</b>", subsection_heading))
                for idx, step in enumerate(treatment_guidance.get("organic_treatment")):
                    tg_elements.append(Paragraph(f"<b>Step {idx+1}:</b> {step}", body_style))
                if treatment_guidance.get("alternative_organic_solutions"):
                    tg_elements.append(Paragraph(f"<i>Organic Alternatives:</i> {treatment_guidance.get('alternative_organic_solutions')}", body_style))
                tg_elements.append(Spacer(1, 6))

            # Chemical medicine table
            if treatment_guidance.get("chemical_treatment_name"):
                tg_elements.append(Paragraph("<b>Chemical Treatment & Dosage:</b>", subsection_heading))
                chem_rows = [
                    [Paragraph("<b>Medicine Name:</b>", body_style), Paragraph(treatment_guidance.get("chemical_treatment_name"), body_style)],
                    [Paragraph("<b>Active Ingredient:</b>", body_style), Paragraph(treatment_guidance.get("active_ingredient", "N/A"), body_style)],
                    [Paragraph("<b>Brand Examples:</b>", body_style), Paragraph(treatment_guidance.get("example_brand_names", "N/A"), body_style)],
                    [Paragraph("<b>Application Method:</b>", body_style), Paragraph(treatment_guidance.get("application_method", "N/A"), body_style)],
                    [Paragraph("<b>Spray Equipment Base:</b>", body_style), Paragraph(f"Dissolve {treatment_guidance.get('mixing_quantity', 'N/A')} in {treatment_guidance.get('water_quantity', '15 Litres')} of water.", body_style)],
                    [Paragraph("<b>Timing & Intervals:</b>", body_style), Paragraph(f"Apply at {treatment_guidance.get('spray_timing', 'N/A')}. Repeat after {treatment_guidance.get('spray_interval', 'N/A')} as required (Max {treatment_guidance.get('number_of_applications', 'N/A')} applications).", body_style)],
                    [Paragraph("<b>Safety Waiting Period:</b>", body_style), Paragraph(f"Harvest wait time: {treatment_guidance.get('waiting_period_before_harvest', 'N/A')}. PPE Required: {treatment_guidance.get('ppe_required', 'N/A')}.", body_style)],
                ]
                chem_table = Table(chem_rows, colWidths=[140, 383])
                chem_table.setStyle(TableStyle([
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 4),
                    ('TOPPADDING', (0,0), (-1,-1), 0),
                    ('LEFTPADDING', (0,0), (-1,-1), 0),
                ]))
                tg_elements.append(chem_table)
                tg_elements.append(Spacer(1, 6))

            # Sprayer Calibration Metrics
            if calculator_metrics:
                tg_elements.append(Paragraph("<b>Sprayer Calibration & Dosage Field Plan:</b>", subsection_heading))
                metrics_rows = [
                    [Paragraph("<b>Land Size:</b>", body_style), Paragraph(f"{calculator_metrics.get('land_size')} {calculator_metrics.get('land_unit')}", body_style)],
                    [Paragraph("<b>Total Field Medicine:</b>", body_style), Paragraph(calculator_metrics.get("total_medicine", "N/A"), body_style)],
                    [Paragraph("<b>Total Field Water:</b>", body_style), Paragraph(calculator_metrics.get("total_water", "N/A"), body_style)],
                    [Paragraph("<b>Sprayer Runs:</b>", body_style), Paragraph(calculator_metrics.get("tanks_count", "N/A"), body_style)],
                    [Paragraph("<b>Per-Tank Mix Dosage:</b>", body_style), Paragraph(f"Mix {calculator_metrics.get('per_tank_dosage', 'N/A')} per tank (Capacity: {calculator_metrics.get('tank_capacity')} L).", body_style)],
                    [Paragraph("<b>Estimated Costs:</b>", body_style), Paragraph(f"Medicine: {calculator_metrics.get('cost_medicine', 'N/A')} | Labor: {calculator_metrics.get('cost_labour', 'N/A')} | Total: {calculator_metrics.get('cost_total', 'N/A')}", body_style)],
                ]
                metrics_table = Table(metrics_rows, colWidths=[140, 383])
                metrics_table.setStyle(TableStyle([
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 4),
                    ('TOPPADDING', (0,0), (-1,-1), 0),
                    ('LEFTPADDING', (0,0), (-1,-1), 0),
                ]))
                tg_elements.append(metrics_table)
                tg_elements.append(Spacer(1, 6))

            # Advisory source
            source = treatment_guidance.get("government_advisory_source")
            updated = treatment_guidance.get("last_updated_date")
            if source:
                tg_elements.append(Paragraph(f"<i>Source: {source} | Last Updated: {updated or 'N/A'}</i>", disclaimer_style))
                
            story.append(KeepTogether(tg_elements))
            story.append(Spacer(1, 10))

        # AI Disclaimer Block
        disclaimer_elements = []
        disclaimer_elements.append(Paragraph("<b>AI Diagnostics Disclaimer:</b>", body_bold))
        disclaimer_text = (
            "This report is generated by an artificial intelligence model (Gemini 1.5 Flash). "
            "AI predictions are for educational and informational purposes only. "
            "Always cross-reference AI recommendations with local agricultural extension offices "
            "or a certified agronomist before applying chemical treatments, fertilizers, or modifying watering management schedules. "
            "CropDiseaseAI is not liable for crop failure, chemical damage, or improper dosage application."
        )
        disclaimer_elements.append(Paragraph(disclaimer_text, disclaimer_style))
        story.append(KeepTogether(disclaimer_elements))

        # If there are more reports in the list, append a PageBreak to separate pages
        if r_idx < len(reports_list) - 1:
            story.append(PageBreak())

    # Build PDF document
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
